all:
    project_dir: "/home/danielsg/16S_QIIME2/test"
    mux_dir: "multiplexed_fastq"
    mapping: "test_mapping_file.tsv"
    admin_email: "danielsg@email.chop.edu"

#try revcomp if you are getting 0 reads when demultiplexing
demux:
    mismatch: 0
    revcomp: false

denoise:
    trim_left_f: 0
    trunc_len_f: 240
    trim_left_r: 0
    trunc_len_r: 240
    n_threads: 6

taxonomy:
    classifier_fp: "/home/danielsg/16S_QIIME2/QIIME2_data/gg-13-8-99-nb-classifier.qza"

diversity:
    sampling_depth: 1000

unassign:
    unassigner_species_fp: "/home/danielsg/16S_QIIME2/unassign_data/unassigner_species.fasta"

dada2:
    rscript: "/home/danielsg/16S_QIIME2/scripts/dada2.R"
    species_training_set: "/home/danielsg/16S_QIIME2/dada2_data/rdp_species_assignment_16.fa.gz"

vsearch:
    db: "/mnt/isilon/microbiome/analysis/biodata/green_genes/current_gg16S.fasta"
    threads: 4
    min_id: 0.97 #minimum identity for query-target match
    weak_id: 0.97 #set lower than min-id and you will get some weaker matches too
    userfields: "query+target+id2+alnlen+mism+gaps+qilo+qihi+tilo+tihi+qs+ts+qrow+trow" #fields for results file, see vsearch documentation for details
    iddef: 2 #the way "identity" is calculated, see vsearch docs for details (it's equal to (matching columns) / (alignment length) excluding terminal gaps)
    fasta_width: 0 #Width of alignment lines in fasta output, set to 0 to eliminate wrapping
    maxaccepts: 1 #Maximum number of hits to accept before stopping the search Default is 1

